version: '3.7'

services:
  api:
    build:
      dockerfile: Dockerfile.srv
      context: .
    restart: unless-stopped

    ports:
      - '3000:3000'

    volumes:
      - ./srv/.env:/app/.env
      - ./srv/prisma:/app/prisma
      - /Users/kugi/Music:/app/lib

  icecast2:
    image: pltnk/icecast2
    container_name: icecast2
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./dockerMisc/icecast.xml:/etc/icecast2/icecast.xml
