FROM node:16-bullseye as front_builder
WORKDIR /app

COPY ./ui /app
COPY ./dockerMisc/run_front.sh /app/run.sh

RUN (cd /app && yarn install --frozen-lockfile && yarn build) && yarn cache clean && npm i -g local-web-server

EXPOSE 3000
CMD ["bash", "/app/run.sh"]
