version: '3.7'

services:
  api:
    build:
      dockerfile: Dockerfile.srv
      context: .
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./srv/.env:/app/.env
      - ./srv/prisma:/app/prisma
      - /Users/kugi/Music:/app/lib
      - ./covers:/app/dist/API/routes/assets/covers

  icecast2:
    image: pltnk/icecast2
    container_name: icecast2
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./dockerMisc/icecast.xml:/etc/icecast2/icecast.xml

  loki:
    depends_on:
      - api
      - grafana
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - ./dockerMisc/grafana:/var/lib/grafana
