version: '3.7'

services:
  api:
    image: kugichka/nesorter-api:2.0.7
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - /home/kugichka/Music:/app/lib
      - ./data/prisma:/app/prisma
      - ./data/covers:/app/dist/API/routes/assets/covers
    environment:
      - CONTENT_ROOT_DIR_PATH=/app/lib
      - LOG_PATH=/tmp/nesorter.log

      - SHOUT_HOST=icecast2
      - SHOUT_PORT=8000
      - SHOUT_MOUNT=neformat.mp3
      - SHOUT_USER=neformat
      - SHOUT_PASSWORD=12345678
      - SHOUT_URL=http://localhost:8000/neformat.mp3
      - SHOUT_DESCRIPTION=Its test stream
      
      - MPV_PATH=mpv
      - MPV_FADE_TIME=0
      - FFMPEG_BITRATE=196
      - FFMPEG_FORMAT=mp3

  front:
    image: kugichka/nesorter-front:2.0.7
    restart: always
    ports:
      - "3000:3000"

  icecast2:
    image: pltnk/icecast2
    container_name: icecast2
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./dockerMisc/icecast.xml:/etc/icecast2/icecast.xml

  loki:
    depends_on:
      - api
      - grafana
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    user: "472"
    volumes:
      - ./dockerMisc/grafana:/var/lib/grafana
