version: '3.7'

services:
  icecast2:
    image: kugichka/nesorter-icecast:2.0.9
    container_name: icecast2
    restart: always
    environment:
      - SHOUT_ADMIN_EMAIL=your@address.com

      - SHOUT_SOURCE_PASSWORD=spass
      - SHOUT_RELAY_PASSWORD=rpass
      - SHOUT_ADMIN_USERNAME=admin
      - SHOUT_ADMIN_PASSWORD=apass

      - SHOUT_SYSTEM_TUNE_LOGLEVEL=3
      - SHOUT_SYSTEM_TUNE_HOSTNAME=localhost
      - SHOUT_SYSTEM_TUNE_CLIENTS=100
      - SHOUT_SYSTEM_TUNE_SOURCES=2
      - SHOUT_SYSTEM_TUNE_THREADPOOL=5
      - SHOUT_SYSTEM_TUNE_QUEUE_SIZE=524288
      - SHOUT_SYSTEM_TUNE_CLIENT_TIMEOUT=30
      - SHOUT_SYSTEM_TUNE_HEADER_TIMEOUT=15
      - SHOUT_SYSTEM_TUNE_SOURCE_TIMEOUT=10
      - SHOUT_SYSTEM_TUNE_BURST_ON_CONNECT=1
      - SHOUT_SYSTEM_TUNE_BURST_SIZE=65535

      - SHOUT_MOUNT=neformat.mp3
      - SHOUT_USER=neformat
      - SHOUT_PASSWORD=12345678
    ports:
      - "8000:8000"

  api:
    image: kugichka/nesorter-api:2.0.9
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - /home/kugichka/Music:/app/lib
      - ./data/prisma:/app/prisma
      - ./data/covers:/app/dist/API/routes/assets/covers
    environment:
      - SHOUT_HOST=icecast2
      - SHOUT_MOUNT=neformat.mp3
      - SHOUT_USER=neformat
      - SHOUT_PASSWORD=12345678
      - SHOUT_URL=http://localhost:8000/neformat.mp3
      - SHOUT_DESCRIPTION=Its test stream

      - MPV_FADE_TIME=0
      - FFMPEG_BITRATE=196
      - FFMPEG_FORMAT=mp3

  front:
    image: kugichka/nesorter-front:2.0.9
    restart: always
    ports:
      - "3000:3000"

  loki:
    depends_on:
      - api
      - grafana
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    user: "472"
    volumes:
      - ./dockerMisc/grafana:/var/lib/grafana
